# Systems Configuration
# This file documents the infrastructure, services, and configurations

platform:
  proxmox:
    description: "Proxmox cluster configuration"
    vault: ""
    vault_entry: ""
    notes: "Virtualization platform hosting the Kubernetes cluster"
  
  kubernetes:
    description: "Kubernetes cluster configuration"
    vault: ""
    vault_entry: ""
    notes: "K8s cluster running on Proxmox for container orchestration"
  
  synology:
    description: "Synology NAS"
    vault: ""
    vault_entry: ""
    notes: "Network attached storage for media and backups"

services:
  kubernetes:
    plex:
      description: "Plex media server"
      namespace: "plex"
      vault: ""
      vault_entry: ""
      notes: "Streaming media server"
    
    sonarr:
      description: "Sonarr TV show management"
      namespace: "sonarr"
      vault: ""
      vault_entry: ""
      notes: "Automated TV show downloads and management"
    
    radarr:
      description: "Radarr movie management"
      namespace: "radarr"
      vault: ""
      vault_entry: ""
      notes: "Automated movie downloads and management"
    
    nzbget:
      description: "NZBGet usenet downloader"
      namespace: "nzbget"
      vault: ""
      vault_entry: ""
      notes: "Usenet download client"
    
    work_calendar_sync:
      description: "Work Calendar Sync service"
      namespace: "calendar-sync"
      vault: ""
      vault_entry: ""
      notes: "Syncs ICS calendar to Google Calendar with timezone handling"
      repository: "https://github.com/jaymart1983/Work-Calendar-Sync"
      ingress: "calendar.iamjason.net"

network:
  ubiquiti:
    description: "Ubiquiti network router"
    vault: ""
    vault_entry: ""
    notes: "Main network router and gateway"
  
  tailscale:
    description: "Tailscale VPN setup"
    vault: ""
    vault_entry: ""
    notes: "Secure VPN mesh network for remote access"

github:
  repos:
    work_calendar_sync:
      url: "https://github.com/jaymart1983/Work-Calendar-Sync"
      description: "ICS to Google Calendar sync service"
      vault: ""
      vault_entry: ""
      workflows:
        - name: "Build and Push Docker Image"
          description: "Builds Docker image and pushes to GitHub Container Registry on push to main"
          triggers: ["push to main"]
